spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/assetstudio}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:133789ss}

# Tells Spring to automatically create your tables based on your Java code
spring.jpa.hibernate.ddl-auto=update

# Tells Spring we are using PostgreSQL syntax
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}