# Tells Spring to connect to the 'assetstudio' database on your local machine
spring.datasource.url=jdbc:postgresql://localhost:5432/assetstudio

# The default superuser name
spring.datasource.username=postgres

# REPLACE THIS with the password you created during the PostgreSQL installation
spring.datasource.password=133789ss

# Tells Spring to automatically create your tables based on your Java code
spring.jpa.hibernate.ddl-auto=update

# Tells Spring we are using PostgreSQL syntax
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect